name: BellCommand
version: '1.2.0'
main: cn.ningmo.bellcommand.BellCommand
api-version: '1.21'
authors: [NingMo]
description: A powerful command item plugin
commands:
  bc:
    description: BellCommand main command
    usage: /<command> [reload|give|list]
    aliases: [bellcommand]
    permission: bellcommand.command
permissions:
  bellcommand.command:
    description: Allows using BellCommand commands
    default: op
  bellcommand.reload:
    description: Allows reloading BellCommand configuration
    default: op
  bellcommand.give:
    description: Allows giving command items
    default: op
  bellcommand.list:
    description: Allows listing command items
    default: op
  bellcommand.use:
    description: Allows using command items
    default: true
