name: BellCommand
version: 1.1.0
main: cn.ningmo.bellcommand.BellCommand
api-version: 1.13
author: ningmengchongshui
description: A powerful command item plugin
website: https://github.com/ningmengchongshui/BellCommand

commands:
  bellcommand:
    description: Plugin main command
    usage: /bellcommand reload
    permission: bellcommand.reload
    aliases: [bc, bell]
    
  clock:
    description: Get a command item
    usage: /clock [itemId]
    permission: bellcommand.clock
    aliases: [bclock, bellclock]
    
  clockremove:
    description: Remove command items
    usage: /clockremove [itemId]
    permission: bellcommand.clock
    aliases: [bclockremove, bellclockremove]

permissions:
  bellcommand.*:
    description: 允许使用所有功能
    default: op
    children:
      bellcommand.clock: true
      bellcommand.reload: true
      bellcommand.item.*: true
  
  bellcommand.clock:
    description: Allows using the clock command
    default: true
  
  bellcommand.reload:
    description: Allows reloading the plugin configuration
    default: op
  
  bellcommand.item.*:
    description: Allows using all command items
    default: true
